# Generated by Django 5.1.5 on 2025-01-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='my_related_obj',
            new_name='course',
        ),
    ]
