# Generated by Django 5.1.5 on 2025-01-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lesson_preview_alter_lesson_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='preview',
        ),
        migrations.AddField(
            model_name='lesson',
            name='can_preview',
            field=models.BooleanField(default=False, help_text='If user does not have access to course, can they see this?'),
        ),
    ]
